name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: legartistech/duckling
  PLATFORMS: linux/amd64,linux/arm64


jobs:
  # stack:
  #   name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macOS-latest, windows-latest]
  #       stack: ["2.5.1"]
  #       ghc: ["8.6.5", "8.8.4", "8.10.3", "9.0.1"]

  #   steps:
  #   - uses: actions/checkout@v2
  #     if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

  #   - uses: haskell/actions/setup@v1
  #     name: Setup Haskell Stack
  #     with:
  #       ghc-version: ${{ matrix.ghc }}
  #       stack-version: ${{ matrix.stack }}

  #   - uses: actions/cache@v2.1.4
  #     name: Cache ~/.stack
  #     with:
  #       path: ~/.stack
  #       key: ${{ runner.os }}-${{ matrix.ghc }}-stack

  #   - name: Build
  #     run: |
  #       stack build duckling:lib --system-ghc --test --bench --no-run-tests --no-run-benchmarks

  #   - name: Test
  #     run: |
  #       stack test --system-ghc

  image:
    runs-on: 'ubuntu-latest'
    # needs: 'stack'

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.branch-name.outputs.current_branch }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Build and push 'latest' tag
        if: steps.branch-name.outputs.is_default == 'true'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest